# -*- coding: utf-8 -*-
from django.conf import settings

def get(key, default):
    return getattr(settings, key, default)

# FORUM Settings
FORUM_BASE_TITLE = get('SLIMBB_FORUM_BASE_TITLE', 'Django Bulletin Board')
FORUM_META_DESCRIPTION = get('SLIMBB_FORUM_META_DESCRIPTION', '')
FORUM_META_KEYWORDS = get('SLIMBB_FORUM_META_KEYWORDS', '')
TOPIC_PAGE_SIZE = get('SLIMBB_TOPIC_PAGE_SIZE', 10)
FORUM_PAGE_SIZE = get('SLIMBB_FORUM_PAGE_SIZE', 20)
SEARCH_PAGE_SIZE = get('SLIMBB_SEARCH_PAGE_SIZE', 20)
USERS_PAGE_SIZE = get('SLIMBB_USERS_PAGE_SIZE', 20)
SIGNATURE_MAX_LENGTH = get('SLIMBB_SIGNATURE_MAX_LENGTH', 1024)
SIGNATURE_MAX_LINES = get('SLIMBB_SIGNATURE_MAX_LINES', 3)
HEADER = get('SLIMBB_HEADER', 'slimbb forum')
NOFOLLOW_LINKS = get('SLIMBB_NOFOLLOW_LINKS', True)
POST_USER_SEARCH = get('SLIMBB_POST_USER_SEARCH', 1)
NOTIFICATION_HANDLER = get('SLIMBB_NOTIFICATION_HANDLER', 'slimbb.subscription.email_topic_subscribers')
JQUERY_URL = get('SLIMBB_JQUERY_URL', '//cdnjs.cloudflare.com/ajax/libs/jquery/2.2.0/jquery.min.js')

# ATTACHMENT Extension
ATTACHMENT_SUPPORT = get('SLIMBB_ATTACHMENT_SUPPORT', True)
ATTACHMENT_UPLOAD_TO = get('SLIMBB_ATTACHMENT_UPLOAD_TO', 'slimbb/attachments')
ATTACHMENT_SIZE_LIMIT = get('SLIMBB_ATTACHMENT_SIZE_LIMIT', 1024 * 1024)

